stages:
  - ai-mr

generate-mr-description:
  stage: ai-mr
  image: node:20-alpine

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

  variables:
    GIT_DEPTH: 0
    GITLAB_API_V4_URL: 'https://gitlab.com/api/v4'

  script:
    - node scripts/generate-mr-desc.js

  allow_failure: true
